-- ==================Categories==================================
create table public.categories (
    id bigint generated by default as identity primary key,

    slug text not null unique,
    name text not null,
    description text,

    created_at timestamptz not null default now()
);

alter table public.categories
    add constraint categories_slug_length
    check (char_length(slug) between 1 and 100);

alter table public.categories
    add constraint categories_name_length
    check (char_length(name) between 1 and 100);


-- =======================Articles=============================
create type article_status as enum (
    'draft',
    'published'
);

create table public.articles (
    id uuid primary key default gen_random_uuid(),
    author_id uuid not null references profiles(id),
    category_id bigint not null references categories(id),
    title text not null,
    slug text not null unique,
    content text not null,
    cover_image text,
    status article_status not null default 'draft',
    reading_time integer,
    published_at timestamptz,
    updated_at timestamptz ,
    created_at timestamptz not null default now(),
   
    constraint articles_reading_time_check
        check (reading_time >= 0),

    constraint articles_slug_length
        check (char_length(slug) between 1 and 200),

    constraint articles_title_length
        check (char_length(title) between 1 and 300)
);