create table public.tags (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    created_at timestamptz not null default now(),

    constraint tags_slug_length
        check (char_length(slug) between 1 and 100),

    constraint tags_name_length
        check (char_length(name) between 1 and 50)
);

create table public.article_tags (
    article_id uuid not null references public.articles(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,

    primary key (article_id, tag_id)
);