-- ============================================================
-- 001_schema.sql
-- Tables, constraints, enum
-- ============================================================

-- Enum
create type article_status as enum ('draft', 'published');

-- Profiles (extend auth.users)
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  display_name  text not null,
  username      text unique,
  avatar_url    text,
  bio           text,
  website_url   text,
  github_url    text,
  linkedin_url  text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint profiles_display_name_length check (char_length(display_name) between 1 and 100),
  constraint profiles_username_length     check (username is null or char_length(username) between 3 and 30),
  constraint profiles_bio_length          check (bio is null or char_length(bio) <= 500)
);

-- Categories
create table public.categories (
  id         bigint generated by default as identity primary key,
  slug       text not null unique,
  name       text not null,
  created_at timestamptz not null default now(),

  constraint categories_slug_length check (char_length(slug) between 1 and 100),
  constraint categories_name_length check (char_length(name) between 1 and 100)
);

-- Articles
create table public.articles (
  id           uuid primary key default gen_random_uuid(),
  author_id    uuid not null references public.profiles(id),
  category_id  bigint not null references public.categories(id),
  title        text not null,
  slug         text not null unique,
  content      text not null,
  cover_image  text,
  status       article_status not null default 'draft',
  reading_time integer,
  published_at timestamptz,
  updated_at   timestamptz not null default now(),
  created_at   timestamptz not null default now(),

  constraint articles_reading_time_check check (reading_time >= 0),
  constraint articles_slug_length        check (char_length(slug) between 1 and 200),
  constraint articles_title_length       check (char_length(title) between 1 and 300)
);

-- Comments
create table public.comments (
  id         uuid primary key default gen_random_uuid(),
  article_id uuid not null references public.articles(id) on delete cascade,
  parent_id  uuid references public.comments(id) on delete cascade,
  author_id  uuid not null references public.profiles(id) on delete cascade,
  content    text not null,
  created_at timestamptz not null default now(),

  constraint comments_content_length check (char_length(content) between 1 and 1000)
);

-- Article Likes
create table public.article_likes (
  article_id uuid not null references public.articles(id) on delete cascade,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (article_id, user_id)
);